[package]
name = "hello-rocket"
version = "0.1.0"
authors = ["Yuri Khomyakov <yuri.khomyakov@ironsrc.com>"]

[dependencies]
rocket = "0.3.17"
rocket_codegen = "0.3.17"
rocket_contrib = "0.3.17"
serde_derive = "1.0.70"
serde = "1.0.70"
serde_json = "1.0.24"
mongodb = "0.3.3"
bson = "0.12.3"